version: '3'
services:
  elasticsearch:
    image: 'elasticsearch:7.6.2'
    environment:
      - discovery.type=single-node
    ports:
      - '9200:9200'
  kibana:
    image: 'kibana:7.6.2'
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH=http://elasticsearch:9200
    ports:
      - '5601:5601'
