name: 'coronamovement'

api:
  component: '@serverless/aws-lambda'
  inputs:
    name: coronamovement-api
    code: ./api
    handler: ./lib/index.handler
    env:
      CONNECT_TO: ${env.CONNECT_TO}
      DB: mongo
      NODE_ENV: production
    region: eu-central-1
    memory: 512
    timeout: 15
apiGateway:
  component: '@serverless/aws-api-gateway'
  inputs:
    region: eu-central-1
    endpoints:
      - path: /register
        method: POST
        function: ${api.arn}
      - path: /user/{id}
        method: GET
        function: ${api.arn}
      - path: /health-data
        method: POST
        function: ${api.arn}
      - path: /{id}/hours
        method: GET
        function: ${api.arn}
      - path: /{id}/summary
        method: GET
        function: ${api.arn}
web:
  component: '@serverless/website'
  inputs:
    code:
      root: ./web
      src: ./build
      hook: npm run build
    region: eu-central-1
    bucketName: mycoronamovement
    domain: web.mycoronamovement.com
