name: 'coronamovement'

api:
  component: '@serverless/aws-lambda'
  inputs:
    name: coronamovement-api
    code: ./api
    handler: ./lib/index.handler
    env:
      CONNECT_TO: ${env.CONNECT_TO}
      API_KEY: ${env.API_KEY}
      AWS_S3_ACCESS_KEY_ID: ${env.AWS_S3_ACCESS_KEY_ID}
      AWS_S3_ACCESS_KEY_SECRET: ${env.AWS_S3_ACCESS_KEY_SECRET}
      AWS_S3_BUCKET_NAME: appfeedback
      AWS_S3_BUCKET_REGION: eu-north-1
      DASHBOARD_AUTH_TOKEN: ${env.DASHBOARD_AUTH_TOKEN}
      APP_AUTH_TOKEN: ${env.APP_AUTH_TOKEN}
      DB: mongo
      NODE_ENV: production
    region: eu-central-1
    memory: 1536
    timeout: 15
    runtime: nodejs12.x
apiGateway:
  component: '@serverless/aws-api-gateway'
  inputs:
    region: eu-central-1
    endpoints:
      - path: /{proxy+}
        method: ANY
        function: ${api.arn}
