name: 'coronamovement'

api:
  component: '@serverless/aws-lambda'
  inputs:
    name: coronamovement-api
    code: ./api
    handler: ./lib/index.handler
    env:
      CONNECT_TO: ${env.CONNECT_TO}
      API_KEY: ${env.API_KEY}
      AWS_S3_ACCESS_KEY_ID: ${env.AWS_S3_ACCESS_KEY_ID}
      AWS_S3_ACCESS_KEY_SECRET: ${env.AWS_S3_ACCESS_KEY_SECRET}
      AWS_S3_BUCKET_NAME: appfeedback
      AWS_S3_BUCKET_REGION: eu-north-1
      DB: mongo
      NODE_ENV: production
    region: eu-central-1
    memory: 512
    timeout: 15
apiGateway:
  component: '@serverless/aws-api-gateway'
  inputs:
    region: eu-central-1
    endpoints:
      - path: /unlock
        method: POST
        function: ${api.arn}
      - path: /register
        method: POST
        function: ${api.arn}
      - path: /user/{id}
        method: GET
        function: ${api.arn}
      - path: /user/{id}
        method: PATCH
        function: ${api.arn}
      - path: /user/{id}
        method: DELETE
        function: ${api.arn}
      - path: /health-data
        method: POST
        function: ${api.arn}
      - path: /{id}/update
        method: GET
        function: ${api.arn}
      - path: /update-everyone
        method: GET
        function: ${api.arn}
      - path: /total
        method: GET
        function: ${api.arn}
      - path: /{id}/hours
        method: GET
        function: ${api.arn}
      - path: /{id}/summary
        method: GET
        function: ${api.arn}
      - path: /{id}/last-upload
        method: GET
        function: ${api.arn}
      - path: should-unlock
        method: GET
        function: ${api.arn}
      - path: feedback
        method: POST
        function: ${api.arn}
      - path: analytics
        method: POST
        function: ${api.arn}
      - path: /fitbit/callback
        method: GET
        function: ${api.arn}
web:
  component: '@serverless/website'
  inputs:
    code:
      root: ./web
      src: ./build
      hook: npm run build
    region: eu-central-1
    bucketName: mycoronamovement
    domain: web.mycoronamovement.com
