# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  lane :alpha do
    upload_to_play_store(
      track: 'alpha',
      json_key: './playstore.json',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      package_name: 'com.wfh-movement.app'
    )
    # slack(message: 'Successfully distributed a new alpha build')
  end

  lane :beta do
    upload_to_play_store(
      track: 'beta',
      json_key: './playstore.json',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      package_name: 'com.wfh-movement.app'
    )
    # slack(message: 'Successfully distributed a new beta build')
  end
end
