name: wfhmovement
description: A new Flutter project.
publish_to: 'none'

version: 1.13.2+75

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.19.3
  http: ^0.13.1
  flutter_hooks: ^0.16.0
  shared_preferences: ^2.0.5
  provider: ^5.0.0
  fl_chart: ^0.9.4
  url_launcher: ^6.0.3
  cookie_jar: ^3.0.1
  dio: ^4.0.0
  dio_cookie_manager: ^2.0.0
  timezone: ^0.7.0
  intl: ^0.17.0
  path_provider: ^2.0.1
  share: ^2.0.1
  package_info: ^2.0.0
  country_list_pick: 1.0.0+5
  auto_size_text: ^3.0.0-nullsafety.0
  flutter_web_auth: ^0.3.0
  flutter_native_timezone: ^1.0.10
  pull_to_refresh: ^1.6.4
  uni_links: ^0.4.0
  clipboard: ^0.1.3
  i18n_extension: ^4.0.0
  after_layout: ^1.1.0
  health:
    path: ../health_package

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/png/
    - assets/locales/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 800
