name: wfhmovement
description: A new Flutter project.

version: 1.4.1+27

environment:
  sdk: '>=2.5.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.18.1
  http: ^0.12.0+4
  health: ^1.0.2+2
  flutter_hooks: ^0.9.0
  shared_preferences: ^0.5.7
  provider: ^4.0.5+1
  fl_chart: ^0.9.4
  url_launcher: ^5.4.10
  cookie_jar: ^1.0.1
  dio: ^3.0.9
  dio_cookie_manager: ^1.0.0
  dio_retry: ^0.1.9-beta
  timezone: any
  intl: any
  path_provider: ^1.6.14
  share: ^0.6.5
  feedback: ^0.3.0
  image: ^2.1.14
  package_info: ^0.4.3
  country_list_pick: ^1.0.0+5
  auto_size_text: ^2.1.0
  flutter_web_auth: ^0.2.4
  pull_to_refresh: ^1.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/png/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 800
