name: wfhmovement
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.5.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.17.4
  http: ^0.12.0+4
  health: ^1.0.2
  flutter_hooks: ^0.9.0
  shared_preferences: ^0.5.7
  provider: ^4.0.5+1
  workmanager: ^0.2.0
  fl_chart: ^0.9.4
  url_launcher: ^5.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
