#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/xandse/Documents/dev/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/xandse/Documents/code/work/gu/corona-movement/health_package"
export "FLUTTER_TARGET=lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "OTHER_LDFLAGS=$(inherited) -framework Flutter"
export "FLUTTER_FRAMEWORK_DIR=/Users/xandse/Documents/dev/flutter/bin/cache/artifacts/engine/ios"
export "FLUTTER_BUILD_NAME=3.0.2"
export "FLUTTER_BUILD_NUMBER=3.0.2"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=false"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=.packages"
