name: health
description: Wrapper for the iOS HealthKit and Android GoogleFit services.
version: 3.0.2
homepage: https://github.com/cph-cachet/flutter-plugins/tree/master/packages/health

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: '>=1.27.0-4.0.pre'

dependencies:
  flutter:
    sdk: flutter
  device_info: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: cachet.plugins.health
        pluginClass: HealthPlugin
      ios:
        pluginClass: HealthPlugin
